package: generated
import-mapping:
  https://raw.githubusercontent.com/unikorn-cloud/core/main/pkg/openapi/common.spec.yaml: github.com/unikorn-cloud/core/pkg/openapi
  https://raw.githubusercontent.com/unikorn-cloud/core/alansy/inst-316/pkg/openapi/common.spec.yaml: github.com/unikorn-cloud/core/pkg/openapi
