apiVersion: v2
name: unikorn-identity
description: A Helm chart for deploying Unikorn's IdP

type: application

version: 1.13.0
appVersion: 1.13.0

icon: https://raw.githubusercontent.com/unikorn-cloud/assets/main/images/logos/dark-on-light/icon.png

dependencies:
- name: unikorn-common
  version: 0.1.16
  repository: https://nscaledev.github.io/uni-helm-common
